info:
  contact: {}
  license: {}
paths:
  /api/v1/health/ping:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"ping": "pong"}'
          schema:
            type: string
      summary: ping
      tags:
      - health
  /api/v1/health/status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: "0"
          schema:
            type: string
      summary: check health status
      tags:
      - health
swagger: "2.0"
